# Generated by Django 5.0.4 on 2024-06-09 06:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0008_alter_educationalmaterialfile_material_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='educationalmaterial',
            name='date_upload',
        ),
        migrations.AddField(
            model_name='educationalmaterialfile',
            name='date_upload',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата загрузки'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='educationalmateriallink',
            name='date_upload',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата загрузки'),
            preserve_default=False,
        ),
    ]
