# Generated by Django 5.0.4 on 2024-05-25 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0004_alter_employee_options_alter_employeecontact_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="name_en",
            field=models.CharField(max_length=255, null=True, verbose_name="Имя"),
        ),
        migrations.AddField(
            model_name="employee",
            name="name_ru",
            field=models.CharField(max_length=255, null=True, verbose_name="Имя"),
        ),
        migrations.AddField(
            model_name="employee",
            name="patronymic_en",
            field=models.CharField(max_length=255, null=True, verbose_name="Отчество"),
        ),
        migrations.AddField(
            model_name="employee",
            name="patronymic_ru",
            field=models.CharField(max_length=255, null=True, verbose_name="Отчество"),
        ),
        migrations.AddField(
            model_name="employee",
            name="position_en",
            field=models.TextField(null=True, verbose_name="Должность"),
        ),
        migrations.AddField(
            model_name="employee",
            name="position_ru",
            field=models.TextField(null=True, verbose_name="Должность"),
        ),
        migrations.AddField(
            model_name="employee",
            name="surname_en",
            field=models.CharField(max_length=255, null=True, verbose_name="Фамилия"),
        ),
        migrations.AddField(
            model_name="employee",
            name="surname_ru",
            field=models.CharField(max_length=255, null=True, verbose_name="Фамилия"),
        ),
        migrations.AddField(
            model_name="employeecontact",
            name="title_en",
            field=models.CharField(max_length=255, null=True, verbose_name="Тип"),
        ),
        migrations.AddField(
            model_name="employeecontact",
            name="title_ru",
            field=models.CharField(max_length=255, null=True, verbose_name="Тип"),
        ),
    ]
