# Generated by Django 5.0.4 on 2024-06-10 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="galleryphoto",
            name="title",
            field=models.CharField(
                default="Воровайки", max_length=255, verbose_name="Название"
            ),
            preserve_default=False,
        ),
    ]
