# Generated by Django 5.0.4 on 2024-05-03 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0002_alter_news_date_created"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="news",
            options={
                "ordering": ["-id"],
                "verbose_name": "Новость",
                "verbose_name_plural": "Новости",
            },
        ),
    ]
