# Generated by Django 5.0.4 on 2024-04-28 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_news_options_alter_news_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='pictures',
        ),
        migrations.AddField(
            model_name='newspicture',
            name='news',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pictures', to='news.news'),
            preserve_default=False,
        ),
    ]
