# Generated by Django 5.0.4 on 2024-05-21 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_news_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-id'], 'verbose_name': 'новость', 'verbose_name_plural': 'новости'},
        ),
        migrations.AlterModelOptions(
            name='newspicture',
            options={'verbose_name': 'иображение', 'verbose_name_plural': 'изображения'},
        ),
    ]
