# Generated by Django 5.0.4 on 2024-04-28 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_remove_news_pictures_newspicture_news'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newspicture',
            options={'verbose_name': 'Изображение новости', 'verbose_name_plural': 'Изображения новостей'},
        ),
    ]
