# Generated by Django 5.0.4 on 2024-05-03 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SupportTicket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_name", models.CharField(max_length=255)),
                ("user_email", models.EmailField(max_length=254)),
                ("subject", models.CharField(max_length=255)),
                ("text", models.TextField()),
            ],
            options={
                "verbose_name": "Обращение",
                "verbose_name_plural": "Обращения",
            },
        ),
    ]
