# Generated by Django 5.0.4 on 2024-05-21 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_supportticket_date_created_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supportticket',
            options={'verbose_name': 'обращение', 'verbose_name_plural': 'обращения'},
        ),
    ]
