# Generated by Django 5.0.4 on 2024-05-21 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_alter_schedule_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedule',
            options={'verbose_name': 'расписание', 'verbose_name_plural': 'расписание'},
        ),
    ]
